### ISSUE TITLE
Notebook Pro doesn't work with Sketch 39.1

### ISSUE THREAD

**Issue by mmcneillsav** [marcosvidal/Sketch-Notebook#74]
I am unable to add notebooks or notes to new files created in Sketch 39.1 using Notebook Pro

I can edit the **text** of notes in files created in previous versions of Sketch, but am unable to add new notes to those files.

**Comment by Ishpoean** [comment]
I'm having a similar problem - Sketch 39.1 and Notebook Pro 0.3

When I select an object and try to create a note, an empty '--nb--sidebar' folder gets created, and I get flipped into an empty '--nb--assets' page. No dialogue window opens to enter text and no sidebar is created

(A similar thing happened when I was on the free version of Notebook a few months ago, which is why I upgraded)

Thanks in advance for any help

**Comment by mmcneillsav** [comment]
My issue was resolved by the developer. He emailed out an update that for some reason I was unable to receive. Once we had a one on one dialog via email I was able to receive the updated file.
