### ISSUE TITLE
'Styles' Menu Missing from Pro Version

### ISSUE THREAD

**Issue by luxlogica** [marcosvidal/Sketch-Notebook#82]
I have just purchased the 'Pro' version of the Notebook plugin, but the 'Styles' menu is missing - ie., in the 'Notebook Pro' menu there is no 'Style' submenu as depicted in this video:

https://vimeo.com/146762950

Have the style presets been removed from the latest version, or am I doing something wrong?

**Comment by volmerf** [comment]
I'm also missing this option in the pro version. Could you please fix this soon?

**Comment by juliansharifi** [comment]
Missing this as well - tried to reinstall and now Notebook isn't coming up in the sketch plugin menu at all in v42

**Comment by patowod** [comment]
I'm also missing this. Even repurchased the plugin, because I thought I was missing it due to Updates that were not initially in Notebook Pro - since it says Free Upgrades are only in Premium Version. 

This would be really good to have. Is there any timing you can give, as to when we could expect the style menu to appear? I have to have a consistent look differing from the default across multiple sketch files. 

Thanks in advance and kind regards.

**Comment by patowod** [comment]
Since you advertised the newest version, are there any news on this @marcosvidal ? It would be nice to know if this is now implemented – I would not really want to buy a third time to find out it's still missing?

**Comment by marcosvidal** [comment]
Make sure you are using the latest version of the plugin. There is an enhanced styling feature now!
